version: 2

updates:
  - package-ecosystem: npm
    directory: '/'
    schedule:
      interval: weekly
      day: monday
      time: '09:00'
      timezone: Asia/Tokyo
    open-pull-requests-limit: 5
    groups:
      patch-and-minor:
        patterns:
          - '*'
        update-types:
          - minor
          - patch
    ignore:
      - dependency-name: '*'
        update-types:
          - version-update:semver-major
    commit-message:
      prefix: chore
      include: scope

  - package-ecosystem: github-actions
    directory: '/'
    schedule:
      interval: monthly
      timezone: Asia/Tokyo
    open-pull-requests-limit: 3
    commit-message:
      prefix: ci
